FROM jorge07/alpine-php:7.1

ARG USER=root
ARG PASSWORD=root

ARG COMPOSER_VERSION=1.3.2
ARG XDEBUG_VERSION=2.5.1

RUN apk add --no-cache \
        php7.1-dev \
        php7.1-pear \
        openssh \
        supervisor \
        autoconf \
        git \
        apache-ant \
        zip \
        wget \
        autoconf \
        gcc \
        make \
        g++ \
        curl \
    && rm -rf /var/cache/apk/* \

    && cd /tmp && wget http://xdebug.org/files/xdebug-${XDEBUG_VERSION}.tgz \
    && tar -zxvf xdebug-${XDEBUG_VERSION}.tgz \
    && cd xdebug-${XDEBUG_VERSION} && phpize \
    && ./configure --enable-xdebug && make && make install \
    && cd \
    && rm -rf /tmp/* \

    && sed -i s/#PermitRootLogin.*/PermitRootLogin\ yes/ /etc/ssh/sshd_config \
    && echo "${USER}:${PASSWORD}" | chpasswd \
    && ssh-keygen -A \

    && curl -sS https://getcomposer.org/installer | php7.1 -- --install-dir=/usr/bin --filename=composer --version=${COMPOSER_VERSION} \
    && composer global require "hirak/prestissimo:0.3.5" \

    && wget https://git.io/psysh \
    && chmod +x psysh \
    && mv psysh /usr/bin/psysh

ADD devfs /

RUN HOST_IP="$(/sbin/ip route|awk '/default/ { print $3 }')" \
    && sed -i "$ a\xdebug.remote_host=${HOST_IP}" /etc/php7.1/conf.d/xdebug.ini

CMD ["supervisord", "--nodaemon", "--configuration", "/etc/supervisor/conf.d/supervisord.conf"]

EXPOSE 22 9000
