FROM jorge07/alpine-php:5.6

ENV USER root
ENV PASSWORD root

ENV COMPOSER_VERSION 1.2.1

RUN apk add --no-cache \
        openssh \
        supervisor \
        git \
        apache-ant \
        zip \
        wget \
        curl \
        php5-xdebug \

    && sed -i s/#PermitRootLogin.*/PermitRootLogin\ yes/ /etc/ssh/sshd_config \
    && echo "${USER}:${PASSWORD}" | chpasswd \
    && ssh-keygen -A \
    && rm -rf /var/cache/apk/* \

    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer --version=${COMPOSER_VERSION} \

    && wget https://phar.phpunit.de/phpunit.phar \
    && chmod +x phpunit.phar \
    && mv phpunit.phar /usr/bin/phpunit \

    && wget https://git.io/psysh \
    && chmod +x psysh \
    && mv psysh /usr/bin/psysh

COPY config/env/profile /etc/profile
COPY config/php/php-dev.ini /etc/php/conf.d/50-setting.ini
COPY config/supervisor/supervisor.conf /etc/supervisor/conf.d/supervisord.conf

ENTRYPOINT ["supervisord", "--nodaemon", "--configuration", "/etc/supervisor/conf.d/supervisord.conf"]

EXPOSE 22 9000
