FROM jorge07/alpine-php:5.6

ARG USER=root
ARG PASSWORD=root

ARG COMPOSER_VERSION=1.2.1

RUN apk add --no-cache \
        openssh \
        supervisor \
        git \
        apache-ant \
        zip \
        wget \
        curl \
        php5-xdebug \

    && sed -i s/#PermitRootLogin.*/PermitRootLogin\ yes/ /etc/ssh/sshd_config \
    && echo "${USER}:${PASSWORD}" | chpasswd \
    && ssh-keygen -A \
    && rm -rf /var/cache/apk/* \

    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer --version=${COMPOSER_VERSION} \
    && composer global require "hirak/prestissimo:0.3.5" \

    && wget https://git.io/psysh \
    && chmod +x psysh \
    && mv psysh /usr/bin/psysh

ADD devfs /

CMD ["supervisord", "--nodaemon", "--configuration", "/etc/supervisor/conf.d/supervisord.conf"]

EXPOSE 22 9000
